FROM nginx:alpine

RUN apk update

# Copiar el certificado SSL y la clave
COPY nginx.crt /etc/nginx/ssl/nginx.crt
COPY nginx.key /etc/nginx/ssl/nginx.key

# Copiar el archivo de configuración de NGINX
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443
