FROM ubuntu:latest

RUN apt-get update && apt install -y curl cron
RUN echo "* * * * * root curl http://server" > /etc/cron.d/spam
RUN echo "*/5 * * * * root curl http://server/?key=key_pato" > /etc/cron.d/key
RUN service cron start

CMD tail -f /dev/null
