FROM nginx:alpine

RUN apk update

# Copiar el archivo de configuración de NGINX
COPY nginx.conf /etc/nginx/nginx.conf
COPY climates.sh /root/climates.sh
RUN chmod 777 /root/climates.sh

# Configura las tareas cron
RUN echo "*	*	*	*	*	/root/climates.sh" >> /var/spool/cron/crontabs/root
RUN crond

# Crear un script para iniciar Nginx y crond
RUN echo -e "#!/bin/sh\ncrond && nginx -g 'daemon off;'" > /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

CMD ["/usr/local/bin/start.sh"]
